export const checkboxLists = {
  Cuisines: [
    { id: "cuisine1", value: "African", checked: false },
    { id: "cuisine2", value: "American", checked: false },
    { id: "cuisine3", value: "British", checked: false },
    { id: "cuisine4", value: "Cajun", checked: false },
    { id: "cuisine5", value: "Caribbean", checked: false },
    { id: "cuisine6", value: "Chinese", checked: false },
    { id: "cuisine7", value: "Eastern European", checked: false },
    { id: "cuisine8", value: "European", checked: false },
    { id: "cuisine9", value: "French", checked: false },
    { id: "cuisine10", value: "German", checked: false },
    { id: "cuisine11", value: "Greek", checked: false },
    { id: "cuisine12", value: "Indian", checked: false },
    { id: "cuisine13", value: "Irish", checked: false },
    { id: "cuisine14", value: "Italian", checked: false },
    { id: "cuisine15", value: "Japanese", checked: false },
    { id: "cuisine16", value: "Jewish", checked: false },
    { id: "cuisine17", value: "Korean", checked: false },
    { id: "cuisine18", value: "Latin American", checked: false },
    { id: "cuisine19", value: "Mediterranean", checked: false },
    { id: "cuisine20", value: "Mexican", checked: false },
    { id: "cuisine21", value: "Middle Eastern", checked: false },
    { id: "cuisine22", value: "Nordic", checked: false },
    { id: "cuisine23", value: "Southern", checked: false },
    { id: "cuisine24", value: "Spanish", checked: false },
    { id: "cuisine25", value: "Thai", checked: false },
    { id: "cuisine26", value: "Vietnamese", checked: false },
  ],

  Diets: [
    { id: "diet1", value: "Gluten Free", checked: false },
    { id: "diet2", value: "Ketogenic", checked: false },
    { id: "diet3", value: "Vegetarian", checked: false },
    { id: "diet4", value: "Lacto-Vegetarian", checked: false },
    { id: "diet5", value: "Ovo-Vegetarian", checked: false },
    { id: "diet6", value: "Vegan", checked: false },
    { id: "diet7", value: "Pescetarian", checked: false },
    { id: "diet8", value: "Paleo", checked: false },
    { id: "diet9", value: "Primal", checked: false },
    { id: "diet10", value: "Whole30", checked: false },
  ],
  Types: [
    { id: "type1", value: "main course", checked: false },
    { id: "type2", value: "side dish", checked: false },
    { id: "type3", value: "dessert", checked: false },
    { id: "type4", value: "appetizer", checked: false },
    { id: "type5", value: "salad", checked: false },
    { id: "type6", value: "bread", checked: false },
    { id: "type7", value: "breakfast", checked: false },
    { id: "type8", value: "soup", checked: false },
    { id: "type9", value: "beverage", checked: false },
    { id: "type10", value: "sauce", checked: false },
    { id: "type12", value: "marinade", checked: false },
    { id: "type13", value: "fingerfood", checked: false },
    { id: "type14", value: "snack", checked: false },
    { id: "type15", value: "drink", checked: false },
  ],
  Intolerances: [
    { id: "intolerance1", value: "Dairy", checked: false },
    { id: "intolerance2", value: "Egg", checked: false },
    { id: "intolerance3", value: "Gluten", checked: false },
    { id: "intolerance4", value: "Grain", checked: false },
    { id: "intolerance5", value: "Peanut", checked: false },
    { id: "intolerance6", value: "Seafood", checked: false },
    { id: "intolerance7", value: "Sesame", checked: false },
    { id: "intolerance8", value: "Shellfish", checked: false },
    { id: "intolerance9", value: "Soy", checked: false },
    { id: "intolerance10", value: "Sulfite", checked: false },
    { id: "intolerance11", value: "Tree Nut", checked: false },
    { id: "intolerance12", value: "Wheat", checked: false },
  ],
};
